### Pytorch中的张量就是元素属同一数据类型的多维矩阵

torch.tensor():相对简单，直接把传入的数值原样转化为张量。只支持一个参数，其功能就是将传入的对象转化成为张量。  
该函数不但支持python中的原声数据类型，还支持numpy类型。  

In [12]:
import torch
import numpy as np
a = torch.tensor(5)
print(a)
anp = np.array([4])
a =  torch.tensor(anp)
print(a)

tensor(5)
tensor([4])


torch.Tensor()函数也可以直接定义一个张量。在使用此函数定义张量的时候，可以指定张量的形状，也可以指定张量的内容。

In [13]:
import torch
a = torch.Tensor(2)
print(a)
b= torch.Tensor(1,2)
print(b)
c = torch.Tensor([2])
print(c)
d = torch.Tensor([1,2])
print(d)
print(torch.is_tensor(d))
print(torch.numel(a))

tensor([2.0239e+29, 4.5664e-41])
tensor([[2.0239e+29, 4.5664e-41]])
tensor([2.])
tensor([1., 2.])
True
2


In [14]:
import torch
print(torch.get_default_dtype())
print(torch.Tensor([1,3]).dtype)

torch.float32
torch.float32


In [15]:
import torch
a = torch.FloatTensor([4])
print(a.dtype)
print(a.type(torch.IntTensor))
print(a.type(torch.DoubleTensor))
print(a.dtype)
print(a.int())
print(a.double())
print(a.mean())
print(a.sqrt())

torch.float32
tensor([4], dtype=torch.int32)
tensor([4.], dtype=torch.float64)
torch.float32
tensor([4], dtype=torch.int32)
tensor([4.], dtype=torch.float64)
tensor(4.)
tensor([2.])


In [16]:
import numpy as np
import torch
nparray = np.array([1,1])
x = torch.from_numpy(nparray)
print(x)
nparray += 1
print(x)

tensor([1, 1])
tensor([2, 2])


In [17]:
nparray = np.array([1,1])
x = torch.from_numpy(nparray)
print(x)
nparray = nparray + 1
print(x)

tensor([1, 1])
tensor([1, 1])


In [18]:
import torch
a = torch.FloatTensor([4])
b = a.cuda()
print(b)
print(b.cpu())
print(b)

tensor([4.], device='cuda:0')
tensor([4.])
tensor([4.], device='cuda:0')


### 4.5生成随机值张量

In [19]:
# 4.5.1设置随机值种子
torch.initial_seed()
torch.manual_seed(2)
torch.initial_seed()
torch.randn(2,3)
print(torch.arange(1,10,step=2))
print(torch.arange(0,10,step=2))
print(torch.linspace(1,9,steps=5))
# 4.5.4生成对数空间的随机值
print(torch.logspace(1,9,steps=5))

tensor([1, 3, 5, 7, 9])
tensor([0, 2, 4, 6, 8])
tensor([1., 3., 5., 7., 9.])
tensor([1.0000e+01, 1.0000e+03, 1.0000e+05, 1.0000e+07, 1.0000e+09])


## 4.6张量间的数学运算

In [20]:
import torch
a = torch.FloatTensor([4])
print(a, a+a)
# 4.6.1PyTorch的运算函数
b = torch.add(a,a)
print(b)
torch.add(a,a,out=c)
print(c)
# 4.6.2PyTorch的自变化运算函数
a.add_(*b)  # 相当于a+=b
print(a)

tensor([4.]) tensor([8.])
tensor([8.])
tensor([8.])
tensor([12.])


## 4.7张量间的数据操作

In [21]:
# 4.7.1用reshape函数实现数据维度的变换
a = torch.tensor([[1,2],[3,4]])
print(torch.reshape(a,(1,-1)))
print(a.reshape((1,-1)))
print(a.view((1,-1)))

tensor([[1, 2, 3, 4]])
tensor([[1, 2, 3, 4]])
tensor([[1, 2, 3, 4]])


在PyTorch中，还可以使用torch.squeeze()对某张量进行压缩（在变形过程中，可以把取值为1的维度去掉）。  
squeeze()函数默认在变形过程中，将输入张量中所有取值为1的维度去掉。如果一个张量中取值为1的维度很多，的纳斯又不想全部去掉，那么可以在函数中通过设定dim参数，选择去掉某一个维度（dim参数所制定的维度必须满足取值为1）。  


In [24]:
# 4.7.4用cat函数实现数据的连接
a = torch.tensor([[1,2],[3,4]])
b = torch.tensor([[5,6],[7,8]])
print(torch.cat([a,b],dim=0))
print(torch.cat([a,b],dim=1))
# 4.7.5用chunk函数实现数据的均匀分割
a = torch.tensor([[1,2],[3,4]])
print(torch.chunk(a,chunks=2,dim=0))
print(torch.chunk(a,chunks=2,dim=1))

tensor([[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]])
tensor([[1, 2, 5, 6],
        [3, 4, 7, 8]])
(tensor([[1, 2]]), tensor([[3, 4]]))
(tensor([[1],
        [3]]), tensor([[2],
        [4]]))


In [37]:
# 4.7.7用torch.gather()函数对于张量数据进行检索
import torch
b = torch.tensor([
    [1,2,3],
    [4,5,6]
])
print(torch.gather(b,dim=1,index=torch.tensor([[1,2],[1,2]])))

tensor([[2, 3],
        [5, 6]])


In [53]:
a = torch.tensor([[3,1],[2,4]])
torch.argmax(a,dim=0)
torch.max(a,dim=0)

torch.return_types.max(
values=tensor([3, 4]),
indices=tensor([0, 1]))