In [1]:
import torch
from torch.autograd import Variable
a = torch.FloatTensor([4])
print(Variable(a))  # 转化为Variable对象
print(Variable(a,requires_grad=True))
print(a.data)

tensor([4.])
tensor([4.], requires_grad=True)
tensor([4.])


<font color=pink>在使用Variable对张量进行转化的时候，可以使用requires_grad参数来指定该张量是否需要梯度计算，并且要求张量的数据类型必须是浮点型，Pytorch不支持整型进行梯度运算。  </font>

In [2]:
import torch
from torch.autograd import Variable
x = torch.ones(2,2,requires_grad=True)
with torch.no_grad():
    y = x * 2
print(y.requires_grad)
print(x.requires_grad)

False
True


### 装饰器(Decorators)是 Python 的一个重要部分。简单地说：他们是修改其他函数的功能的函数。他们有助于让我们的代码更简短，也更Pythonic（Python范儿）。

In [3]:
@torch.no_grad()
def doubler(x):
    return x * 2
z = doubler(x)
print(z.requires_grad)

False


In [6]:
import torch
from torch.autograd import variable
x = Variable(torch.ones(2,2),requires_grad=True)
print(x,x.grad_fn)
m = x + 2
print(m.grad_fn)
print(m.grad_fn(x))

tensor([[1., 1.],
        [1., 1.]], requires_grad=True) None
(tensor([[1., 1.],
        [1., 1.]], requires_grad=True), None)
