In [4]:
import torch
import torch.nn as nn
input = torch.autograd.variable(torch.randn(2))
print(input)
print(nn.Sigmoid()(input))
print(nn.LogSigmoid()(input))

tensor([1.1878, 0.5943])
tensor([0.7664, 0.6444])
tensor([-0.2661, -0.4395])


F:\Anaconda3\lib\site-packages\torch\autograd\__init__.py:257: UserWarning: torch.autograd.variable(...) is deprecated, use torch.tensor(...) instead
  warnings.warn("torch.autograd.variable(...) is deprecated, use torch.tensor(...) instead")
F:\Anaconda3\lib\site-packages\torch\autograd\__init__.py:258: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  return torch.tensor(*args, **kwargs)
